package Views.Maintenances.Product;

import Views.Maintenances.Product.Products.Products;
import Views.Maintenances.Product.TypesMotorCycle.TypesMotorCycle;
import Views.Maintenances.Product.Brands.Brands;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JTabbedPane;

/**
 *
 * @author kalfe
 */
public class ProductsMain extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductsMain
     */
    public ProductsMain() {
        initComponents();
        setClosable(true); 
        JTabbedPane tabbedPane = new JTabbedPane();

        // Agregar los paneles como pestañas en el JTabbedPane
        Brands brandsPanel = new Brands();
        tabbedPane.addTab("Marcas", brandsPanel);
        
        TypesMotorCycle typesPanel = new TypesMotorCycle();
        tabbedPane.addTab("Tipos de motocicletas", typesPanel);
        
        Products productsPanel = new Products();
        tabbedPane.addTab("Productos", productsPanel);
        
        tabbedPane.setPreferredSize(new Dimension(930, 500));
        
        //System.out.println("El JTabbedPane es visible: " + tabbedPane.isVisible());
        tabbedPane.isVisible();
        jPanel_backGround.add(tabbedPane, BorderLayout.CENTER);
        

        jPanel_backGround.revalidate();
        jPanel_backGround.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_backGround = new javax.swing.JPanel();

        jPanel_backGround.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_backGround, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_backGround, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_backGround;
    // End of variables declaration//GEN-END:variables
}
