package Views;

import Views.Maintenances.Customer.CustomersMain;
import Views.Maintenances.Product.ProductsMain;
import Views.Sales.SalesMain;
import java.awt.BorderLayout;
import java.awt.FlowLayout;

/**
 *
 * @author kalfe
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBttn_viewCustomers = new javax.swing.JButton();
        jBttn_viewManteProducts = new javax.swing.JButton();
        jBttn_sales = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane_Views = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jBttn_viewCustomers.setText("Customers");
        jBttn_viewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttn_viewCustomersActionPerformed(evt);
            }
        });

        jBttn_viewManteProducts.setText("Products");
        jBttn_viewManteProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttn_viewManteProductsActionPerformed(evt);
            }
        });

        jBttn_sales.setText("Realizar venta");
        jBttn_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttn_salesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBttn_viewCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBttn_viewManteProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBttn_sales)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jBttn_viewCustomers)
                .addGap(67, 67, 67)
                .addComponent(jBttn_viewManteProducts)
                .addGap(65, 65, 65)
                .addComponent(jBttn_sales)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, 460));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 100));

        jDesktopPane_Views.setBackground(new java.awt.Color(102, 102, 102));
        jDesktopPane_Views.setForeground(new java.awt.Color(102, 102, 102));
        jDesktopPane_Views.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane_ViewsLayout = new javax.swing.GroupLayout(jDesktopPane_Views);
        jDesktopPane_Views.setLayout(jDesktopPane_ViewsLayout);
        jDesktopPane_ViewsLayout.setHorizontalGroup(
            jDesktopPane_ViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jDesktopPane_ViewsLayout.setVerticalGroup(
            jDesktopPane_ViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane_Views, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 980, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttn_viewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttn_viewCustomersActionPerformed
        CustomersMain internalFrame = new CustomersMain();
        jDesktopPane_Views.add(internalFrame);
        internalFrame.setSize(jDesktopPane_Views.getSize()); 
        internalFrame.setVisible(true);
    }//GEN-LAST:event_jBttn_viewCustomersActionPerformed

    private void jBttn_viewManteProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttn_viewManteProductsActionPerformed
        // TODO add your handling code here:
        ProductsMain internalFrame = new ProductsMain();
        jDesktopPane_Views.add(internalFrame);
        internalFrame.setSize(jDesktopPane_Views.getSize()); 
        internalFrame.setVisible(true);
    }//GEN-LAST:event_jBttn_viewManteProductsActionPerformed

    private void jBttn_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttn_salesActionPerformed
        // TODO add your handling code here:
        SalesMain internalFrame = new SalesMain();
        jDesktopPane_Views.add(internalFrame);
        internalFrame.setSize(jDesktopPane_Views.getSize());
        internalFrame.setVisible(true);
    }//GEN-LAST:event_jBttn_salesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttn_sales;
    private javax.swing.JButton jBttn_viewCustomers;
    private javax.swing.JButton jBttn_viewManteProducts;
    private javax.swing.JDesktopPane jDesktopPane_Views;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
