/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Maintenances.Product.TypesMotorCycle;

/**
 *
 * @author kalfe
 */
public class TypesMotroCycle extends javax.swing.JPanel {

    /**
     * Creates new form TypesMotroCycle
     */
    public TypesMotroCycle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titleType = new javax.swing.JLabel();
        typesMotorCycleTextField = new javax.swing.JTextField();
        jBttn_NewType = new javax.swing.JButton();
        jBttn_EditType = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_TypesMotorCycle = new javax.swing.JTable();
        jBttn_ViewTypes = new javax.swing.JButton();
        jBttn_DeleteType = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titleType.setText("Tipo de Motocicleta:");
        add(jLabel_titleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        add(typesMotorCycleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 110, -1));

        jBttn_NewType.setText("Crear");
        add(jBttn_NewType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jBttn_EditType.setText("Editar");
        add(jBttn_EditType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jTable_TypesMotorCycle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_TypesMotorCycle);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 230));

        jBttn_ViewTypes.setText("Mostrar");
        add(jBttn_ViewTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, -1));

        jBttn_DeleteType.setText("Eliminar");
        add(jBttn_DeleteType, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttn_DeleteType;
    private javax.swing.JButton jBttn_EditType;
    private javax.swing.JButton jBttn_NewType;
    private javax.swing.JButton jBttn_ViewTypes;
    private javax.swing.JLabel jLabel_titleType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_TypesMotorCycle;
    private javax.swing.JTextField typesMotorCycleTextField;
    // End of variables declaration//GEN-END:variables
}
